version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: certificaciones_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: certificaciones_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - certificaciones_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: certificaciones_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - certificaciones_network

volumes:
  mysql_data:

networks:
  certificaciones_network:
    driver: bridge

